package net.socialgamer.cah;

import java.io.File;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.List;


public class UpdateHandlerList {

  private static final List<String> EXCLUDE = Arrays.asList("UpdateHandlerList", "Handler",
      "Handlers");

  /**
   * @param args
   */
  public static void main(final String[] args) throws Exception {
    final String dir = "src/net/socialgamer/cah/handlers/";
    final File outFile = new File(dir + "Handlers.java");
    assert outFile.canWrite();
    assert outFile.delete();
    assert outFile.createNewFile();
    final PrintWriter writer = new PrintWriter(outFile);

    writer.println("// This file is automatically generated. Do not edit.");
    writer.println("package net.socialgamer.cah.handlers;");
    writer.println();
    writer.println("import java.util.HashMap;");
    writer.println("import java.util.Map;");
    writer.println();
    writer.println();
    writer.println("public class Handlers {");
    writer.println("  public final static Map<String, Class<? extends Handler>> LIST;");
    writer.println();
    writer.println("  static {");
    writer.println("    LIST = new HashMap<String, Class<? extends Handler>>();");

    final File d = new File(dir);
    final File[] files = d.listFiles();
    for (final File f : files) {
      System.out.println(f.getName());
      final String fileName = f.getName().split("\\.")[0];
      if (EXCLUDE.contains(fileName) || !f.getName().split("\\.")[1].equals("java")) {
        continue;
      }
      writer.println("    LIST.put(" + fileName + ".OP, " + fileName + ".class);");
    }

    writer.println("  }");
    writer.println("}");
    writer.flush();
    writer.close();

  }
}

// package net.socialgamer.cah.handlers;
//
// import java.util.HashMap;
// import java.util.Map;
//
//
// public class Handlers {
// public final static Map<String, Class<? extends Handler>> LIST;
//
// static {
// LIST = new HashMap<String, Class<? extends Handler>>();
// LIST.put(new RegisterHandler().getOp(), RegisterHandler.class);
// }
// }
